In [3]:
import numpy as np

In [2]:
# Array Skalar

skalar_1 = 5
skalar_2 = np.array(5)

print(type(skalar_2))

<class 'numpy.ndarray'>


In [ ]:
# Array vector, matrix, tensor

vector_1 = np.array([1, 2, 3])
matrix_1 = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
matrix_2 = np.array([1,2,3])
tensor_1 = np.array([
    [[1,2], [3,4]], 
    [[5,6], [7,8]]
    ])

print(vector_1)
print()
print(matrix_1)
print()
print(matrix_2)
print()
print(tensor_1)
print()


[1 2 3]

[[1 2 3]
 [3 4 5]
 [6 7 8]]

[1 2 3]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [ ]:
# Matrix Inspection

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2], [3,4], [5,6]])
C = np.array([1,2,3,4,5,6])

print("A")
print(A)
print(A.ndim)
print(A.shape)
print(A.size)
print(len(A))
print()

print("B")
print(B)
print(B.ndim)
print(B.shape)
print(B.size)
print(len(B))
print()

print("C")
print(C)
print(C.ndim)
print(C.shape)
print(C.size)
print(len(C))
print()

A
[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
2

B
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6
3

C
[1 2 3 4 5 6]
1
(6,)
6
6



In [ ]:
# Matrix Slicing

A = np.array([1,2,3,4,5,6])
B = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print("A")
print(A)
print(A[1]) #Call a value from a vector based on the index, start from 0
print(A[1:3]) #Call multiple value from a vector basec on the start index and ending on the end index, counting from 0
print()

print("B")
print(B)
print(B[1,2]) #Call a value from a matrix based on the dimension index, start from 0 dimension and 0 index
print(B[1:3, 1:3]) #Call multiple value from a matrix base on the start dimension index and ending on the end of the dimension index, counting from 0
print()


A
[1 2 3 4 5 6]
2
[2 3]

B
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[ 6  7]
 [10 11]]



In [ ]:
# Matrix Operation
# Must be the same size

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[2,3,4], [5,6,7]])

print(A)
print()
print(B)
print()
print(A+B)
print()
print(A-B)
print()
print(A*B)
print()

[[1 2 3]
 [4 5 6]]

[[2 3 4]
 [5 6 7]]

[[ 3  5  7]
 [ 9 11 13]]

[[-1 -1 -1]
 [-1 -1 -1]]

[[ 2  6 12]
 [20 30 42]]



In [6]:
# Matrix Operation

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[2,3,4], [5,6,7]])

# Concatenate
print("Concatenate")
print()
C = np.concatenate((A,B), axis=0)
D = np.concatenate((A,B), axis=1)
print(C)
print()
print(D)
print()

# Transpose
print("Transpose")
print()
my_array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(my_array)
print()
print(my_array.transpose())
print()

# Reshape
print("Reshape")
print()

print(A)
print()
print(A.reshape(3,2))
print()
print(A.reshape(6))
print()

E = np.arange(1,13)
print(E)
print()
print(E.reshape(3,4))
print()

# Ravel
print("Ravel")
print()

F = E.reshape(3,4)
print(F.ravel())
print()


Concatenate

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]

[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]

Transpose

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Reshape

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Ravel

[ 1  2  3  4  5  6  7  8  9 10 11 12]



In [ ]:
# dot Product

A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1,2,3], [4,5,6]])

print(A)
print()
print(B)
print()
print(A.dot(B))
print()
print(B.dot(A))

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]

[[22 28]
 [49 64]]


In [ ]:
# dot Inverse

A = np.array([[3,4], [2,7]])

print(A)
print(np.linalg.det(A))

A_inv = np.linalg.inv(A)
print(A_inv)
print()
print(A.dot(A_inv))

[[3 4]
 [2 7]]
13.000000000000005
[[ 0.53846154 -0.30769231]
 [-0.15384615  0.23076923]]

[[1.00000000e+00 1.11022302e-16]
 [5.55111512e-17 1.00000000e+00]]


In [ ]:
from scipy import stats

# Numerical Desc

my_array = np.array([[5,6,3,3],[7,7,7,7], [5,8,9,3]])

print(my_array)
mean_1 = np.mean(my_array)
median_1 = np.median(my_array)
mode_1 = stats.mode(my_array.ravel())

print("mean: ", mean_1)
print("median: ", median_1)
print("mode: ", mode_1)
print("Q1, Q2, Q3: ", np.percentile(my_array, [25,50,75]))

[[5 6 3 3]
 [7 7 7 7]
 [5 8 9 3]]
mean:  5.833333333333333
median:  6.5
mode:  ModeResult(mode=array([7]), count=array([4]))
Q1, Q2, Q3:  [4.5 6.5 7. ]
