In [1]:
# Import Module
import numpy as np
import random

In [ ]:
# Bahas UTS

In [ ]:
# Nomor 1
# Boleh gak usah bikin input
list1 = [1,2,3,4]
list2 = [4,5,6,7]

# Kalo Pake input
list3 = list(map(int, input().split()))
print(list3)

def periksa(list):
    count = 0
    for i in range(len(list)-1):
        if list[i] > list[i+1]:
            count -= 1
        elif list[i] < list[i+1]:
            count += 1
            
    if count == len(list)-1:
        return "Meningkat"
    elif count == (len(list)-1) * -1:
        return "Menurun"
    else:
        return "Tidak Keduanya"
    
print(periksa(list1))
print(periksa(list2))
print(periksa(list3))

In [2]:
# Nomor 2

userNum = int(input("User Number: "))

maxNum = 1000
minNum = 0

while True:
    randNum = random.randrange(minNum,maxNum)
    print("Computer Guess: ", (randNum))
    userInput = int(input("Jawaban User [Benar = 1, Kebesaran = 2, Kekecilan = 3]: "))
    if userInput == 1:
        print("Yeyyy Bener")
        break
    elif userInput == 2:
        maxNum = randNum
    elif userInput == 3:
        minNum = randNum
    


Computer Guess:  170
Computer Guess:  435
Computer Guess:  588
Computer Guess:  575
Computer Guess:  486
Computer Guess:  556
Computer Guess:  497
Computer Guess:  518
Yeyyy Bener


In [12]:
# Nomor 3

# A
a = np.arange(25)
print("Array: ",a)

# B
b = a.reshape(5,5)
print("Matrix: \n",b)

# C
c = b.sum(axis=1)
print("Sum: ",c)

# D
d = np.median(b, axis=0)
print("med: ",d)

# E
bigthanmean = []
for char in a:
    if char > a.mean():
        bigthanmean.append(char)
print("Bigger Than Mean: ",bigthanmean)
        
# F
genap = 0
ganjil = 0
for char in a:
    if char % 2 == 0:
        genap += 1
    else:
        ganjil += 1
print(genap, ganjil)

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Matrix: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Sum:  [ 10  35  60  85 110]
med:  [10. 11. 12. 13. 14.]
Bigger Than Mean:  [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
13 12


In [14]:
# Data Frame

# Mengingat Kembali Dictionary
dict_1 = {"Nama": "Budi",
          "Gender": "Male",
          "Age": 18}

print(dict_1)
print(dict_1["Gender"])
print(dict_1.keys())
print(dict_1.values())

{'Nama': 'Budi', 'Gender': 'Male', 'Age': 18}
Male
dict_keys(['Nama', 'Gender', 'Age'])
dict_values(['Budi', 'Male', 18])


In [32]:
# Module Untuk Data Frame
import pandas as pd

In [29]:
# List bisa Jadi Series
# Series Itu 1 Dimension
list_siswa = ["Wilbert", "Felix", "Brandon", "Solas", "Sulaiman"]
list_angka = [1,2,3,4,5]
list_random = ["text", True, 4, "a"]
series_siswa = pd.Series(list_siswa)
series_angka = pd.Series(list_angka)
series_random = pd.Series(list_random)

# Indexnya bisa dispecify
series_ibukota = pd.Series(["Jakarta", "Tokyo", "London"], index=["Indonesia", "Japan", "UK"])

# print(list_siswa)
# print(series_siswa)
# print(series_angka)
# print(series_random)

print(series_ibukota)
print(series_ibukota[1])
print(series_ibukota["Japan"])
print()

series_ibukota = pd.Series(["Jakarta", "Tokyo", "London"], index=[1,2,3])
print(series_ibukota)
print(series_ibukota[1])
print()

series_ibukota = pd.Series(["Jakarta", "Tokyo", "London"], index=[4,5,6])
print(series_ibukota)
print(series_ibukota[4])
print()


Indonesia    Jakarta
Japan          Tokyo
UK            London
dtype: object
Tokyo
Tokyo

1    Jakarta
2      Tokyo
3     London
dtype: object
Jakarta

4    Jakarta
5      Tokyo
6     London
dtype: object
Jakarta



In [30]:
# Dictionary Bisa Jadi Series
series_budi = pd.Series(dict_1)
print(series_budi)

Nama      Budi
Gender    Male
Age         18
dtype: object


In [43]:
# Sorting

print(series_siswa)
series_siswa2 = pd.Series(["Feli", "Alis", "Angel"])

series_gabungan = series_siswa.append(series_siswa2)

# inplace biar langsung masuk ke vaiable
# Drop biar Index awal tidak Kesimpan
# Sorting by Index
series_gabungan.sort_index(inplace=True)

# Reset Index Biar Indecnya gak double
# series_gabungan = series_gabungan.reset_index()
series_gabungan.reset_index(drop=True, inplace=True)

# Sort by Values
series_gabungan.sort_values(inplace=True)

series_gabungan.reset_index(drop=True, inplace=True)

print(series_gabungan)
print(series_gabungan[0])

0     Wilbert
1       Felix
2     Brandon
3       Solas
4    Sulaiman
dtype: object
0        Alis
1       Angel
2     Brandon
3        Feli
4       Felix
5       Solas
6    Sulaiman
7     Wilbert
dtype: object
Alis


C:\Users\kanek\AppData\Local\Temp\ipykernel_25656\316590091.py:6: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series_gabungan = series_siswa.append(series_siswa2)


In [45]:
#Data Frame

dict_1 = {"Nama": "Ani", "Umur": 21, "WNI": True, "Gender": "Female", "GPA": 3.5}
dict_2 = {"Nama": "Budi", "Umur": 20, "WNI": True, "Gender": "Male", "GPA": 3.3}
dict_3 = {"Nama": "Charlie", "Umur": 23, "WNI": False, "Gender": "Male", "GPA": 3.2}
dict_4 = {"Nama": "Devi", "Umur": 20, "WNI": True, "Gender": "Female", "GPA": 3.7}

df_siswa = pd.DataFrame([dict_1, dict_2, dict_3, dict_4])
print(df_siswa)

      Nama  Umur    WNI  Gender  GPA
0      Ani    21   True  Female  3.5
1     Budi    20   True    Male  3.3
2  Charlie    23  False    Male  3.2
3     Devi    20   True  Female  3.7


In [57]:
# Print Umur Siswa
print(df_siswa["Umur"])

# Print Siswa Dengan Lokasi 2
print(df_siswa.loc[2])

# Print Siswa Dengan Gender Male
print(df_siswa[df_siswa["Gender"] == "Male"])

# Print Mean dari umur siswa dengan GPA lebih besar sama dengan 3.5
print(df_siswa[df_siswa["GPA"] >= 3.5]["Umur"].mean())


0    21
1    20
2    23
3    20
Name: Umur, dtype: int64
Nama      Charlie
Umur           23
WNI         False
Gender       Male
GPA           3.2
Name: 2, dtype: object
      Nama  Umur    WNI Gender  GPA
1     Budi    20   True   Male  3.3
2  Charlie    23  False   Male  3.2
20.5
