# Import Tensorflow

In [21]:
import tensorflow as tf
print(tf.__version__)

2.15.0


# Tensor Object

## Creating Tensor Object

In [7]:
a = tf.constant([2,2])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [8]:
b = tf.constant([3,4])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

## Variable vs Constant

### Variable

In [16]:
a = tf.Variable([5,2])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 2], dtype=int32)>

In [23]:
a.assign([1,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

## Matric Calculation

In [40]:
a = tf.constant([[1,2], [4, 2]])
b = tf.constant([[3,4], [5,6]])

### Addition and Subtraction

In [41]:
c = tf.add(a,b)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [9, 8]], dtype=int32)>

In [42]:
c = a+b
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [9, 8]], dtype=int32)>

In [43]:
d = tf.subtract(a,b)
d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -2],
       [-1, -4]], dtype=int32)>

In [44]:
d = a-b
d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -2],
       [-1, -4]], dtype=int32)>

### Multiplication

#### Vector Multiplication

In [45]:
e = tf.multiply(a,b)
e

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  8],
       [20, 12]], dtype=int32)>

#### Matrix Multiplication

In [46]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 16],
       [22, 28]], dtype=int32)>

In [47]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 16],
       [22, 28]], dtype=int32)>

## Squeeze (Reduce Dimension)

In [48]:
import numpy as np

In [50]:
a = tf.constant(np.random.randint(0, 100, 224*224*3*2), shape=(2, 224, 224, 3))
print(a)
tf.squeeze(a)

tf.Tensor(
[[[[62 14 52]
   [86 87  6]
   [42 81 35]
   ...
   [58  7 92]
   [99 51 66]
   [12 79 40]]

  [[71 23 91]
   [67 18 11]
   [81 19 59]
   ...
   [52 63 94]
   [63  8 76]
   [61 28 64]]

  [[75 17 17]
   [45 47 50]
   [25 40 15]
   ...
   [12 23 89]
   [46 43 11]
   [78 21 76]]

  ...

  [[72 43 75]
   [31 60 85]
   [93 52 39]
   ...
   [65 79 65]
   [74 39  3]
   [16 49 51]]

  [[87 39 72]
   [12 50 89]
   [32  5 74]
   ...
   [40 17 68]
   [41 34 45]
   [93 11 67]]

  [[45 37 66]
   [19 99 91]
   [23 98 69]
   ...
   [ 5 61 51]
   [61 21 55]
   [39 66 11]]]


 [[[62 68 14]
   [47 25 88]
   [73  7  2]
   ...
   [41 54 85]
   [97 12 17]
   [21 78 56]]

  [[13  8  7]
   [83 45 28]
   [61 16 10]
   ...
   [71 30  4]
   [76 45 23]
   [27 65 11]]

  [[27 14 39]
   [ 4 13 84]
   [13  5 92]
   ...
   [86 38 80]
   [48 78 70]
   [22 46 46]]

  ...

  [[69 86 24]
   [90 22 85]
   [ 8 61 91]
   ...
   [25 76 74]
   [30  0 55]
   [29 45 92]]

  [[99 37 86]
   [34  7 46]
   [89 65 60]
 

<tf.Tensor: shape=(2, 224, 224, 3), dtype=int64, numpy=
array([[[[62, 14, 52],
         [86, 87,  6],
         [42, 81, 35],
         ...,
         [58,  7, 92],
         [99, 51, 66],
         [12, 79, 40]],

        [[71, 23, 91],
         [67, 18, 11],
         [81, 19, 59],
         ...,
         [52, 63, 94],
         [63,  8, 76],
         [61, 28, 64]],

        [[75, 17, 17],
         [45, 47, 50],
         [25, 40, 15],
         ...,
         [12, 23, 89],
         [46, 43, 11],
         [78, 21, 76]],

        ...,

        [[72, 43, 75],
         [31, 60, 85],
         [93, 52, 39],
         ...,
         [65, 79, 65],
         [74, 39,  3],
         [16, 49, 51]],

        [[87, 39, 72],
         [12, 50, 89],
         [32,  5, 74],
         ...,
         [40, 17, 68],
         [41, 34, 45],
         [93, 11, 67]],

        [[45, 37, 66],
         [19, 99, 91],
         [23, 98, 69],
         ...,
         [ 5, 61, 51],
         [61, 21, 55],
         [39, 66, 11]]],


    