In [1]:
import numpy as np
import pandas as pd
import sklearn.metrics as metrics

In [3]:
data = pd.read_excel("./lol.xlsx")
data

,ID,Gender,Ever Married,Graduated,Profession,Spending Score,Family Size,Actual Segmentation,Predicted Segmentation
0,462809,Male,No,No,Healthcare,Low,4,B,B
1,462643,Fcmalc,Yes,Yes,Engineer,Average,3,C,A
2,466315,Female,Yes,Yes,Engineer,Low,1,B,B
3,461735,Male,Yes,Yes,Lawyer,High,2,C,C
4,462669,Female,Yes,Yes,Entertainment,High,6,A,A
5,461319,Male,Yes,No,Artist,Average,2,D,C
6,460156,Male,No,Yes,Healthcare,Low,3,A,B
7,464347,Female,No,Yes,Healthcare,Low,3,D,D
8,465015,Female,Yes,Yes,Engineer,Low,3,B,B
9,465176,Female,Yes,Yes,Artist,Average,4,A,A


In [12]:
metrics.precision_recall_fscore_support(data["Actual Segmentation"], data["Predicted Segmentation"])

(array([0.875, 0.8  , 0.625, 1.   ]),
 array([0.7       , 0.88888889, 0.83333333, 0.8       ]),
 array([0.77777778, 0.84210526, 0.71428571, 0.88888889]),
 array([10,  9,  6,  5], dtype=int64))

In [11]:
metrics.accuracy_score(data["Actual Segmentation"],  data["Predicted Segmentation"])

0.8