## Data Types

### Even-Odd Sum

In [1]:
list = [2, 57, 18, 60, 17, 1, 6, 59, 19, 64, 87, 17, 69, 83, 92, 55, 5, 12, 22, 73, 25, 83]
sum = 0

for i in list :
    if (i % 2 == 0) :
        sum = sum + i

print(sum)

276


### String Length Counter

In [2]:
str = input("String : ")
len(str)

20

In [5]:
length = 0
for i in str :
    length = length + 1

print(length)

20


### Finding Unique Elements

In [10]:
list = []

list_len = int(input("List Length: "))
for i in range(list_len) :
    element = int(input())
    list.append(element)

print(list)

[2, 2, 1, 3, 4]


In [11]:
unique_list = []

for i in list :
    occur = 0
    for j in list :
        if (j == i) :
            occur = occur + 1
    
    if (occur <= 1) :
        unique_list.append(i)

print(unique_list)

[1, 3, 4]


## Looping

### Factorial Calculator

In [18]:
val = int(input("Input a Number: "))

factorial_mult = 1
factorial = 1

for i in range(val) :
    factorial = factorial * factorial_mult
    factorial_mult = factorial_mult + 1

print(factorial)

120


### Pattern Printer

In [30]:
rows = int(input("Rows : "))

for i in range(rows) :
    if (i == 0) :
        print("*")
    elif (i == rows - 1) :
        for j in range(i+1) :
            print("*", end='')
    else :
        print("*", end='')
        for j in range(i - 1) :
            print(" ", end='')
        print("*")


*
**
* *
*  *
*   *
*    *
*******

### Palindrome

In [34]:
str = input("String : ")

palindrome = ''
for i in range(len(str)) :
    j = -1 + (-1 * i)
    palindrome = palindrome + str[j]

if palindrome == str :
    print(f"{str} is a Palindrome")
else :
    print(f"{str} isn't a Palindrome")

ala is a Palindrome


## Function

### Circle Area Calculator

In [35]:
pi = 3.14
def circle_area(radius) :
    return (radius**2) * pi

circle_area(2)

12.56

### String Reverser

In [37]:
def str_reverse(string) :
    reversed = ''
    for i in range(len(string)) :
        reversed = reversed + string[-1 + (i * -1)]
    return reversed

str_reverse("My Name is Wilbert")

'trebliW si emaN yM'

### Exponent Calculator

#### With Loop

In [49]:
def exp_calc_loop(a, b) :
    total = a
    for i in range(b-1) :
        total = total * a
    return total

exp_calc_loop(3,3)

27

#### Without Loop

In [48]:
def exp_calc_no_loop(a, b) :
    return a ** b

exp_calc_no_loop(2, 3)

8

## Indexing & Slicing

### Middle Elements

In [71]:
list = ["Dragon", "Fire", "Water", "Snake"]

def mid_extract(list) :
    middle = (len(list)-1)/2
    if (len(list) % 2 != 0) :
        print(list[round(middle)])
    else :
        print(f"{list[int(middle - 0.5)]} or {list[int(middle + 0.5)]}")

mid_extract(list)

Fire or Water


### Vowel Extractor

In [74]:
def vowel_extract(string) :
    list = []
    for char in string :
        if (char == 'a') or (char == 'i') or (char == 'u') or (char == 'e') or (char == 'o') :
            list.append(char)
    return(list)

vowel_extract("Wilbert")

['i', 'e']

### List Reverser

In [80]:
def list_reverse(list) :
    reversed = []
    for i in range(len(list)) :
        reversed.append(list[-1 + (i * -1)])
    return reversed

list = [2, 3, 4]
list_reverse(list)

[4, 3, 2]

## Basic Operation

### Calculator Function

In [85]:
def calculator(a, b, operator) :
    if operator == '+' :
        return a + b
    elif operator == '-' :
        return a - b
    elif operator == '*' or operator == 'x':
        return a * b
    elif operator == '/' :
        if b == 0 :
            return "Can't be divided"
        else :
            return a / b
    else :
        return "Wrong Operator Input"
    
calculator(1, 0, '/')

"Can't be divided"

### Simple Interest Calculator

In [87]:
def interest_calc(principal, rate, time) :
    for i in range(time) :
        principal = principal + (principal * rate)
    return principal

interest_calc(1000, 0.2, 3)

1728.0

In [89]:
def fibonacci(N) :
    list = [0, 1]
    for i in range(N - 2) :
        sum = list[i] + list[i + 1]
        list.append(sum)
    return list

fibonacci(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

## Vector

### Load Numpy Library

In [90]:
import numpy as np

### Vector Addition

In [91]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

vector1 + vector2

array([5, 7, 9])

### Vector Dot Product

In [92]:
def vector_dot(vector1, vector2) :
    return np.dot(vector1, vector2)

vector_dot(vector1, vector2)

32

### Vector Magnitude

In [93]:
def magnitude(vector) :
    return np.linalg.norm(vector)

magnitude(vector1)

3.7416573867739413

## Matrix

### Matrix Addition

In [95]:
matrix1 = np.array([[1,2,3],
                  [2,3,4],
                  [5,4,6]])

matrix2 = np.array([[3,2,4],
                   [6,7,8],
                   [4,5,6]])

matrix1 + matrix2

array([[ 4,  4,  7],
       [ 8, 10, 12],
       [ 9,  9, 12]])

### Matrix Transposition

In [96]:
matrix1.T

array([[1, 2, 5],
       [2, 3, 4],
       [3, 4, 6]])

### Matrix Multiplication

### Matrix Dot Product

In [99]:
np.dot(matrix1, matrix2)

array([[27, 31, 38],
       [40, 45, 56],
       [63, 68, 88]])