# Needed Libraries

In [2]:
import numpy as np

# Material

## Looping

In [ ]:
limit = 5

# For loop
for i in range(5) : # Dibaca Untuk i dalam rentang 0 - 4
    print(i) # Print i

''' 
Cara kerjanya for loop diatas gmn?
Loop diatas akan memprint i sebanyak 5x dimana i akan mulai dari 
0 dan bertambah 1 setiap iterasi berlangsung sampai limit 
''' 

# While Loop
while limit < 10 : # Membuat Batasan While Loop
    print(limit) # Print limit
    limit += 1 # Membuat limi t bertambah


THE POWER OF FOR LOOP

In [3]:
# For loop sangatlah sering digunakan dalam python krn compatible denagn function function yang kerap digunakan

# Enumerate
list = ["Ayam", "Sapi", "Babi"]

for index, element in enumerate(list) :
    print(index, element)

# Range

# zip
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica", "Vicky")

for element in zip(a, b) :
    print(element)

0 Ayam
1 Sapi
2 Babi
('John', 'Jenny')
('Charles', 'Christy')
('Mike', 'Monica')


## List

In [14]:
# What is List? Basicly an array in python

studentList = ["Saira", "Vincent", "Dea", "Derrick", "Chara"]


print(studentList)
# List dapat di looping

# List Indexing
print(studentList[0]) # Mengambil Value Pertama dari suatu list
print(studentList[-1]) # Mengambil Value Terakhir dari suatu list
print(studentList[0 :]) # Print semua value dari awal sampe akhir
print(studentList[0:2]) # Print semua value dari index ke 0 sampai index ke 1
print(studentList[:-1]) # Print semua value kecuali value terakhir

['Saira', 'Vincent', 'Dea', 'Derrick', 'Chara']
Saira
Chara
['Saira', 'Vincent', 'Dea', 'Derrick', 'Chara']
['Saira', 'Vincent']
['Saira', 'Vincent', 'Dea', 'Derrick']


## Vector & Matrix

##### Creating a Matrix, Vector, and Tensor

What is a vector? basicly just a numpy representarion of a list but with much more use case

In [9]:
vector_1 = np.array([1, 2, 3])
matrix_1 = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
matrix_2 = np.array([[1,2,3]])
tensor_1 = np.array([
    [[1,2], [3,4]], 
    [[5,6], [7,8]]
    ])

print("Vector :")
print(vector_1)
print("\n Matrix 1 :")
print(matrix_1)
print("\n Matrix 2 : ")
print(matrix_2)
print("\n Tensor 1 : ")
print(tensor_1)
print()


Vector :
[1 2 3]

 Matrix 1 :
[[1 2 3]
 [3 4 5]
 [6 7 8]]

 Matrix 2 : 
[[1 2 3]]

 Tensor 1 : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



##### Matrix Inspection

In [14]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2], [3,4], [5,6]])
C = np.array([1,2,3,4,5,6])

print("A")
print("A Matrix :")
print(A)
print(f"A Matrix Dimension : {A.ndim}")
print(f"A Matrix Shape : {A.shape}")
print(f"A Matrix Size : {A.size}")
print(f"A Matrix Length : {len(A)}")
print()

print("B")
print("B Matrix :")
print(B)
print(f"B Matrix Dimension : {B.ndim}")
print(f"B Matrix Shape : {B.shape}")
print(f"B Matrix Size : {B.size}")
print(f"B Matrix Length : {len(B)}")
print()

print("C")
print("C Matrix :")
print(C)
print(f"C Matrix Dimension : {C.ndim}")
print(f"C Matrix Shape : {C.shape}")
print(f"C Matrix Size : {C.size}")
print(f"C Matrix Length : {len(C)}")
print()

A
A Matrix :
[[1 2 3]
 [4 5 6]]
A Matrix Dimension : 2
A Matrix Shape : (2, 3)
A Matrix Size : 6
A Matrix Length : 2

B
B Matrix :
[[1 2]
 [3 4]
 [5 6]]
B Matrix Dimension : 2
B Matrix Shape : (3, 2)
B Matrix Size : 6
B Matrix Length : 3

C
C Matrix :
[1 2 3 4 5 6]
C Matrix Dimension : 1
C Matrix Shape : (6,)
C Matrix Size : 6
C Matrix Length : 6



##### Matrix Slicing

In [15]:
A = np.array([1,2,3,4,5,6])
B = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print("A")
print(A)
print(A[1]) #Call a value from a vector based on the index, start from 0
print(A[1:3]) #Call multiple value from a vector basec on the start index and ending on the end index, counting from 0
print()

print("B")
print(B)
print(B[1,2]) #Call a value from a matrix based on the dimension index, start from 0 dimension and 0 index
print(B[1:3, 1:3]) #Call multiple value from a matrix base on the start dimension index and ending on the end of the dimension index, counting from 0
print()

A
[1 2 3 4 5 6]
2
[2 3]

B
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[ 6  7]
 [10 11]]

