In [1]:
import numpy as np

In [17]:
vector = np.array([1, 2, 3]) # Vector
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [2, 4, 5]]) # Matrix

matrix2 = np.array([[5, 6],
                   [8, 9],
                   [4, 5]])

matrix = np.array([[1, 2, 3]])

tensor = np.array([[[1, 2, 3],
                    [4, 5, 5]],
                    [[1, 2, 3]]])

In [5]:
matrix1 + matrix2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [8]:
matrix1 - matrix2

array([[-4, -4, -4],
       [-4, -4, -4]])

In [9]:
matrix1 * matrix2

array([[ 5, 12, 21],
       [32, 45, 60]])

In [20]:
matrix1.dot(matrix2)

array([[33, 39],
       [84, 99],
       [62, 73]])

In [21]:
matrix = np.arange(1, 101).reshape(10, 10)

In [22]:
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [24]:
matrix.reshape(2, 50)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [27]:
matrix.sum(axis=0) # Axis = 0 -> By Baris || = 1 -> By Kolom

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [28]:
matrix.mean()

50.5

In [30]:
np.median(matrix)

50.5

In [31]:
from scipy import stats

stats.mode(matrix.ravel())

ModeResult(mode=1, count=1)

In [32]:
matrix.ravel()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])