## Sistem Persamaan Linear
Sistem Persamaan Linear biasa

1. Direct Method
2. Indirect Method

- **Gauss Seidel Method** :
    Mencari nilai persamman dengan *Starting Value Random.* ( Mendekati Best Answer )
    - Value < Tresshold (Epsilon)

### Test Question

**Number 1**
1. 10a + 4b + 5c= 8
2. a + 6b + c = 5
3. 3a + b + 6c = 10

**Steps**
- Change Linear Equation to Matrix form \
    [10 4 5] \
    [1 6 1] \
    [3 1 6]

- Absolute the Matrix (Change all Negative Values to Positive) \
    [10 4 5] \
    [1 6 1] \
    [3 1 6] 

- Indentify Diagonally Dominant (Convergent) \
    10 > 4 + 5 (True) \
    6 > 1 + 1 (True) \
    6 > 3 + 1 (True) \
    ***All Line Must be True***

- Search Equation for All of the Variable \
    a = (8 - 4b - 5c) / 10 \
    b = (5 - a- c) / 6 \
    c = (10 - 3a - b) / 10

- Initialize & Iterate Variable (Iterate to Epsilon) \
    **Initialize** \
    a = 0 \
    b = 0 \
    c = 0 \
    
    **Iterate 0** (Use The Newest Value) \
    a = (8 - 4b - 5c) / 10 = (8 - 4(0) - 5(0)) / 10 = 0.8 \
    b = (5 - a - c) / 6 = (5 - 0.8 - 0) / 6 = 0.7 \
    c = (10 - 3a - b) / 10 = (10 - 3(0.8) - 0.7) / 10 = 1.15 \
    ... and so on

### Code

In [2]:
# Import Module / Library

import numpy as np

In [44]:
# Initialize Variable

Xs = np.array([
    # Soal 1
    [
        [10, 4, 5],
        [1, 6, 1],
        [3, 1, 6]
    ],
    # Soal 2
    [
        [9, 2, 3, 2],
        [4, 11, 2, 3],
        [1, -4, 8, -1],
        [5, 3, -6, 16]
    ]
], dtype=object)

Ys = np.array([
    # Soal 1
    [8, 5, 10],
    # Soal 2
    [12, 9, 6, 21]
], dtype=object)

In [45]:
# Gauss Seidel Function
# Epsilon & Total Iteration (t) -> From Question

def gauss_seidel(x, y, epsilon = 0.01, t = 20) :
    # Change List to Array (if not an array yet)
    x = np.array(x)
    y = np.array(y)
    
    # Get Diagonal Absolute
    diags = np.diag(np.abs(x))
    # diags = [10, 6, 6] <- What stored in diags
    
    # Fill value in diagonals with 0
    np.fill_diagonal(x, 0)
    
    # Search Value of diagonal
    # axis = 0 (default) : Column
    # axis = 1 : row
    off_diag = np.sum(np.abs(x), axis=1)
    # off_diags = [9, 2, 4] <- Value of off_diag
    
    # Check Diagonally Dominant or not (Convergency)
    if not np.all(diags > off_diag) :
        return False
    
    # Change all x to negative
    x = -x
    
    # Initiate Matrix with values of 0
    # x[0].shape -> guarenteed present
    mat_old = np.zeros(x[0].shape)
    
    # Iteration
    # First Loop
    for i in range(t) :
        # Copy data from mat_old to mat_new
        mat_new = np.array(mat_old)
         
        # Second Loop for each variable
        for j, row in enumerate(x) :
            # mat_new[0] = [0, 0, 0]
            # row[0] = [0, -4, -5]
            mat_new[j] = (y[j] + np.dot(mat_new, row)) / diags[j]
        
        # Display variable data for each Iteration
        print(f"Iter-{i} : {mat_new}")
      
        # Calculate Eucladean Distance
        dx = np.sqrt(np.dot(mat_new - mat_old, mat_new - mat_old))
        if dx < epsilon : 
            return True
        
        # Update mat_old   
        mat_old = mat_new
        
    return False    

In [47]:
# Print Array

for i, (x, y) in enumerate(zip(Xs, Ys)) :
    print(f"Problem {i + 1}")
    print(f"X = {x}")
    print(f"Y = {y}")
    
    if(gauss_seidel(x, y)) :
        print(f"Convergen!\n")
    else :
        print(f"Not Convergen!\n")

Problem 1
X = [[10, 4, 5], [1, 6, 1], [3, 1, 6]]
Y = [8, 5, 10]
Iter-0 : [0.8  0.7  1.15]
Iter-1 : [-0.055       0.65083333  1.58569444]
Iter-2 : [-0.25318056  0.61124769  1.69138233]
Iter-3 : [-0.29019024  0.59980132  1.7117949 ]
Iter-4 : [-0.29581798  0.59733718  1.71501946]
Convergen!

Problem 2
X = [[9, 2, 3, 2], [4, 11, 2, 3], [1, -4, 8, -1], [5, 3, -6, 16]]
Y = [12, 9, 6, 21]
Iter-0 : [1.33333333 0.33333333 0.75       1.11458333]
Iter-1 : [0.76157407 0.10090488 0.8445786  1.37230541]
Iter-2 : [0.72442707 0.02692894 0.84444926 1.39773584]
Iter-3 : [0.73525807 0.01607833 0.84084889 1.3950355 ]
Iter-4 : [0.73946952 0.01593797 0.83991473 1.39339543]
Convergen!

